app = "bot-scalp-btc"

[build]
  dockerfile = "Dockerfile"

[env]
  # NÃO coloque segredos aqui. Defina TELEGRAM_TOKEN e CHAT_ID usando: 
  # fly secrets set TELEGRAM_TOKEN="seu_token" CHAT_ID="seu_chat_id"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
